### PR TITLE
Remove debug fruit

### PR DESCRIPTION
**Pull request by tsirakisn**
Original PR & discussion here: https://github.com/OpenXT/linux-xen-argo/pull/9
After some discussion, it was determined that a function-based (rather than a macro-based) approach is desired for the future, so this PR contains only the commits needed to remove the DEBUG_* fruit macros. Moving to a new PR for a more professional branch name.

### CODE REVIEW

**Comment by tsirakisn** [comment]
> @tsirakisn did you compile with and without debug to ensure both still work?

Yes, both are compiling.

**Comment by jandryuk** [comment]
Thanks @tsirakisn and @dpsmith.

**Comment by eric-ch** [comment]
Build [$10123](http://openxt-builder.ainfosec.com:8010/#/builders/3/builds/10123)

**Comment by jandryuk** [comment]
Will merge soon.

**Pull request merged**
