### PR TITLE
Apply viptables patches and add 4.19 kernel support

### PR DESCRIPTION
**Pull request by tsirakisn**
Remaining argo PRs will follow in the near future. Wanted to get @dozylynx 's viptables port and the 4.19 support in first.

OXT-1502
OXT-1616

### CODE REVIEW

**Comment by dozylynx** [comment]
Please could my sign off in the commits be rewritten as:
Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>

Otherwise looks good. Thanks.

**Comment by tsirakisn** [comment]
@dozylynx sure no problem. And you want Signed-off-by and not Co-authored-by, correct? Or was that a typo

**Comment by dozylynx** [comment]
`Signed-off-by` please -- thanks

**Comment by tsirakisn** [comment]
@dozylynx updated. I have both of us signing off now, I hope that's what you meant.

**Pull request merged**
